name: $(Date:yyyyMMdd)$(Rev:.r)

pool:
  name: Default

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Unit Tests
  inputs:
    command: 'test'
    projects: '**/Tests*.csproj'
    testRunTitle: 'Unit Tests'

- task: PowerShell@2
  displayName: Yarn
  inputs:
    targetType: 'inline'
    script: |
      "Yarn version: "
      yarn --version
      
      "Node version: "
      node --version
      
      cd Web
      cd app
      yarn
      yarn prod
      cd ..
      cd ..

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration Release --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
