UPDATE Player SET Color = '#9e9e9e'
UPDATE Player SET Color = '#f44336' WHERE PlayerId = 1
UPDATE Player SET Color = '#e91e63' WHERE PlayerId = 4
UPDATE Player SET Color = '#9c27b0' WHERE PlayerId = 2
UPDATE Player SET Color = '#673aB7' WHERE PlayerId = 8
UPDATE Player SET Color = '#3f51b5' WHERE PlayerId = 14
UPDATE Player SET Color = '#2196f3' WHERE PlayerId = 20
UPDATE Player SET Color = '#03a9f4' WHERE PlayerId = 23
UPDATE Player SET Color = '#00bcd4' WHERE PlayerId = 60
UPDATE Player SET Color = '#009688' WHERE PlayerId = 38
UPDATE Player SET Color = '#4cAf50' WHERE PlayerId = 39
UPDATE Player SET Color = '#8bc34a' WHERE PlayerId = 40
UPDATE Player SET Color = '#cddc39' WHERE PlayerId = 43
UPDATE Player SET Color = '#ffeb3b' WHERE PlayerId = 47
UPDATE Player SET Color = '#ffc107' WHERE PlayerId = 52
UPDATE Player SET Color = '#ff9800' WHERE PlayerId = 53
UPDATE Player SET Color = '#ff5722' WHERE PlayerId = 56
UPDATE Player SET Color = '#795548' WHERE PlayerId = 57
UPDATE Player SET Color = '#607d8B' WHERE PlayerId = 59